finalproject/cal/urls.py
from django.urls import include, re_path,path
from . import views

app_name = 'cal'
urlpatterns = [
    re_path(r'^index/$', views.index, name='index'),
    re_path(r'^calendar/$', views.CalendarViewNew.as_view(), name='calendar'),
    path("calenders/", views.CalendarView.as_view(), name="calendars"),

    path('event/new/<int:event_id>', views.event, name='event_new'),
	re_path(r'^event/edit/(?P<event_id>\d+)/$', views.event, name='event_edit'),
    re_path(r'^all-event-list/$', views.AllEventsListView, name="all_events"),
    # path("all_event_list/", views.AllEventsListView.as_view, name="all_events"),
    # re_path(r'^event/approve/$', views.event_approve, name='event_approve'),


]

finalproject/finalproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings
from rdv.views import (
    rdv
    ) 

from account.views import (
    home,
    # settings,
    ProfileUpdateView,
    prof,
    registration_view,
    account_view,
    logout_view,
    login_view,
    must_authenticate_view,
    registerlogin_view,
    activate_user,
)


urlpatterns = [
    path('',home , name = "home"),
    # path('settings/', settings, name="settings"),
    path('account/', account_view, name="account"),
    path('admin/', admin.site.urls),
    path('authen', registerlogin_view, name="registerlogin_view"),
    path('profile-update/<int:med_id>', ProfileUpdateView.as_view(), name='profile-update'),
    path('profile/<int:med_id>', prof, name='profile'),

    path('logout/' , logout_view, name="logout"),
    
    path('must_authenticate/', must_authenticate_view, name="must_authenticate"),
    path('register/', registration_view, name="register"),
    path('activate-user/<uidb64>/<token>',activate_user, name='activate'),


    path('rdv/', rdv, name="rdv"),

    path('admin/', admin.site.urls),
    path('', include('cal.urls')),
    path('', include('medecin.urls')),
    path('',include('historique.urls')),
    path('',include('staff.urls')),
    path('',include('annonce.urls')),


    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='account/password_reset_done.html'),
     name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='account/password_reset_form_password.html'), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='account/password_reset_form.html'), name='password_reset'),
    
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='account/password_reset_complete.html'),
     name='password_reset_complete'),
    ]

from django.conf import settings 
from django.conf.urls.static import static    

urlpatterns +=  static(settings.MEDIA_URL, document_root =settings.MEDIA_ROOT)

finalproject/templates/calendarapp/calendar.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}Event Calendar{% endblock title %}

{% block extracss %}
  <link href="{% static 'calender/main.css' %}" rel="stylesheet" />
{% endblock extracss %}



{% block content %}

            <div class="col">
                <div id="calendar" style="margin: 100px 100px auto"></div>
            </div>

            <div class="modal fade show" id="eventModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered" role="document">
                    <div class="modal-content">
                        <div class="modal-header bg-primary">
                            <h5 class="modal-title text-white" id="exampleModalLongTitle">Add New Event</h5>
                            <button id="modalClose1" type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <form method="post">
                            {% csrf_token %}
                            <div class="modal-body">
                                <div class="form-group">
                                    <label for="recipient-name" class="col-form-label">Phone number:</label>
                                    {{ form.Phone_number }}
                                </div>
                                <div class="form-group">
                                  <label for="recipient-name" class="col-form-label">Sender:</label>
                                  {{ form.Sender }}
                              </div>
                              <div class="form-group">
                                <label for="recipient-name" class="col-form-label">Receiver (Doctors Only):</label>

                                {{ form.Receiver }} 
                            </div>
                                <div class="form-group">
                                    <label for="message-text" class="col-form-label">Description:</label>
                                    {{ form.description }}
                                </div>
                                <div class="form-group">
                                    <label for="message-text" class="col-form-label">Start Date:</label>
                                    {{ form.start_time }}
                                </div>

                            </div>
                            <div class="modal-footer">
                                <button id="modalClose2" type="button" class="btn btn-danger">Close</button>
                                <button type="submit" class="btn btn-primary">Save</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

{% block extrascripts %}
  <script src="{% static 'calender/main.js' %}"></script>
  <script>
      document.addEventListener('DOMContentLoaded', function() {
        var calendarEl = document.getElementById('calendar');
        var today = new Date();

        var calendar = new FullCalendar.Calendar(calendarEl, {
          headerToolbar: {
            left: 'prev,next today',
            center: 'title',
            right: 'dayGridMonth,timeGridWeek,timeGridDay,list'
          },
          initialDate: today,
          navLinks: true, // can click day/week names to navigate views
          selectable: true,
          selectMirror: true,
          select: function(arg) {
            console.log('clicked')
            var modal = document.getElementById('eventModal')
            modal.style.display = 'block'
            calendar.unselect()
          },
          // THIS KEY WON'T WORK IN PRODUCTION!!!
          // To make your own Google API key, follow the directions here:
          // http://fullcalendar.io/docs/google_calendar/
          // googleCalendarApiKey: 'AIzaSyCqCxjjLtjbtkX37aOtWB8OfwBLy_6QuYk',

          // bangladesh Holidays
          // events: 'bn.bd#holiday@group.v.calendar.google.com',
          // eventClick: function(arg) {
          //   if (confirm('Are you sure you want to delete this event?')) {
          //     arg.event.remove()
          //   }
          // },
          editable: false,
          dayMaxEvents: true, // allow "more" link when too many events
           // events: {{events|safe}}



           events: {{events|safe}}
          // events = [
          //           {% for i in events%}
          //           Phone_number: "{{ i.Phone_number}}",
          //           start:"{{ i.start_time.strftime("%Y-%m-%dT%H:%M:%S")",
          //           // detail:'{{ i.get_html_url}}',

          //           {% endfor %}

          //         ]

        });

        calendar.render();
      });
      const closeBtn1 = document.getElementById('modalClose1');
      const closeBtn2 = document.getElementById('modalClose2');
      closeBtn1.addEventListener('click',()=>{
        const eventModal = document.getElementById('eventModal')
        eventModal.style.display = 'none';
      });
      closeBtn2.addEventListener('click',()=>{
        const eventModal = document.getElementById('eventModal')
        eventModal.style.display = 'none';
      });
  </script>
{% endblock extrascripts %}

finalproject/templates/calendarapp/cant_access.html
<p>Cant access this page , Your are not a doctor </p>

finalproject/templates/calendarapp/dashboard.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}Event Dashboard{% endblock title %}

{% block breadcrumb %}
    <div>
        <h1><i class="fa fa-dashboard"></i> Dashboard</h1>
        <p>Event Dashboard</p>
    </div>
    <ul class="app-breadcrumb breadcrumb">
        <li class="breadcrumb-item"><i class="fa fa-home fa-lg"></i></li>
        <li class="breadcrumb-item"><a href="#">Dashboard</a></li>
    </ul>
{% endblock breadcrumb %}

{% block content %}
<div class="row">
    <div class="col-md-6 col-lg-3">
        <div class="widget-small primary coloured-icon">
            <i class="icon fa fa-files-o fa-3x"></i>
            <div class="info">
                <h4>Total Completed Events</h4>
                <p><b>{{ total_event }}</b></p>
            </div>
        </div>
    </div>
    <div class="col-md-6 col-lg-3">
        <div class="widget-small info coloured-icon">
            <i class="icon fa fa-thumbs-o-up fa-3x"></i>
            <div class="info">
                <h4>Total Running Events</h4>
                <p><b>{{ running_events.count }}</b></p>
            </div>
        </div>
    </div>
    <div class="col-md-6 col-lg-3">
        <div class="widget-small warning coloured-icon">
            <i class="icon fa fa-users fa-3x"></i>
            <div class="info">
                <h4>Total Participants</h4>
                <p><b>10</b></p>
            </div>
        </div>
    </div>
    <div class="col-md-6 col-lg-3">
        <div class="widget-small danger coloured-icon">
            <i class="icon fa fa-star fa-3x"></i>
            <div class="info">
                <h4>Stars</h4>
                <p><b>500</b></p>
            </div>
        </div>
    </div>
    <div class="col-md-12">
        <div class="tile">
            <div class="tile-body">
                <div class="table-responsive">
                    <div id="sampleTable_wrapper" class="dataTables_wrapper container-fluid dt-bootstrap4 no-footer">
                        <div class="row">
                            <div class="col-sm-12">
                                <table class="table table-hover table-bordered dataTable no-footer" id="sampleTable" role="grid" aria-describedby="sampleTable_info">
                                    <thead>
                                        <tr role="row">
                                            <th class="sorting_asc" tabindex="0" aria-controls="sampleTable" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Name: activate to sort column descending" style="width: 261.641px;">SL</th>
                                            <th class="sorting" tabindex="0" aria-controls="sampleTable" rowspan="1" colspan="1" aria-label="Position: activate to sort column ascending" style="width: 417.312px;">Event Name</th>
                                            <th class="sorting" tabindex="0" aria-controls="sampleTable" rowspan="1" colspan="1" aria-label="Office: activate to sort column ascending" style="width: 189.281px;">Start Time</th>
                                            <th class="sorting" tabindex="0" aria-controls="sampleTable" rowspan="1" colspan="1" aria-label="Age: activate to sort column ascending" style="width: 102.141px;">End Time</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for event in latest_events %}
                                            <tr role="row" class="odd">
                                                <td class="sorting_1">{{ forloop.counter }}</td>
                                                <td>{{ event.title }}</td>
                                                <td>{{ event.start_time }}</td>
                                                <td>{{ event.end_time }}</td>
                                            </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>
{% endblock content %}

{% block extrascripts %}
    <script type="text/javascript" src="{% static 'js/plugins/jquery.dataTables.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/plugins/dataTables.bootstrap.min.js' %}"></script>
    <script type="text/javascript">$('#sampleTable').DataTable();</script>
{% endblock extrascripts %}

finalproject/templates/calendarapp/edit.html
                    {% for event in events_month %}
                        {% if event.is_active == True%}
                      <div class="fc-event">
                          <h3>{{ event.Phone_number }}</h3>
                          <h3>receiver : {{ event.Receiver }}</h3>
                          <p>At: {{ event.start_time }}</p>
                      </div>
                        {% endif %}
                    {% empty %}
                      <p>No Running Events Found</p>
                    {% endfor %}

finalproject/templates/calendarapp/email.html
{% autoescape off %}


Hi {{user.first_name}}

we would like to inform u that your request to submit a RDV from mr : {{receiver.last_name }} {{receiver.first_name}} has been seccessfully Approved ! 

dont forget , the date is : {{date}}

Urs, QuickHealth Team!


{% endautoescape %}

finalproject/templates/calendarapp/event_approval.html
<p>Event approval page </p>
{{form}}

finalproject/templates/calendarapp/events_list.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}Event List{% endblock title %}

{% block breadcrumb %}

{% endblock breadcrumb %}

{% block content %}
<div class="row" style="margin: 100px 40px auto">
    <div class="col-md-12">
        <div class="tile">
            <div class="tile-body">
                <div class="table-responsive">
                    <div id="sampleTable_wrapper" class="dataTables_wrapper container-fluid dt-bootstrap4 no-footer">
                        <div class="row">
                            <div class="col-sm-12">
                                <table class="table table-hover table-bordered dataTable no-footer" id="sampleTable" role="grid" aria-describedby="sampleTable_info">
                                    <thead>
                                        <tr role="row">
                                            <th class="sorting_asc" tabindex="0" aria-controls="sampleTable" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Name: activate to sort column descending" style="width: 130.00px;">Nom Et Prenom</th>
                                            <th class="sorting" tabindex="0" aria-controls="sampleTable" rowspan="1" colspan="1" aria-label="Position: activate to sort column ascending" style="width: 300px;">Description</th>
                                            <th class="sorting" tabindex="0" aria-controls="sampleTable" rowspan="1" colspan="1" aria-label="Position: activate to sort column ascending" style="width: 117.312px;">Numero de telephone</th>
                                            <th class="sorting" tabindex="0" aria-controls="sampleTable" rowspan="1" colspan="1" aria-label="Office: activate to sort column ascending" style="width: 139.281px;">Date</th>
                                            <th class="sorting" tabindex="0" aria-controls="sampleTable" rowspan="1" colspan="1" aria-label="Age: activate to sort column ascending" style="width: 102.141px;">Statue</th>
                                            <th class="sorting" tabindex="0" aria-controls="sampleTable" rowspan="1" colspan="1" aria-label="Age: activate to sort column ascending" style="width: 49.99px;">Lien</th>                                            
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for event in events %}
                                            <tr role="row" class="odd">
                                                <td class="sorting_1">{{ event.Sender.full_name }}</td>
                                                <td style="width: 300px"> {{ event.description }}</td>
                                                <td >{{ event.Sender.phone_number }}</td>
                                                <td>{{ event.start_time }}</td>
                                                <form method="post" action="{% url 'cal:all_events' %}">
                                                    {% csrf_token %}
                                                <td> <input type="submit" name="approve" id="{{event.id}}" value="{{event.id}}"> </td>
                                                <td><a href="{../../../event/edit/{{event.id}}">Modifier</a></td>
                                            </form>

                                            </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>
{% endblock content %}

{% block extrascripts %}
    <script type="text/javascript" src="{% static 'js/plugins/jquery.dataTables.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/plugins/dataTables.bootstrap.min.js' %}"></script>
    <script type="text/javascript">$('#sampleTable').DataTable();</script>
{% endblock extrascripts %}