finalproject/cal/urls.py
from django.urls import include, re_path,path
from . import views

app_name = 'cal'
urlpatterns = [
    re_path(r'^index/$', views.index, name='index'),
    re_path(r'^calendar/$', views.CalendarViewNew.as_view(), name='calendar'),
    path("calenders/", views.CalendarView.as_view(), name="calendars"),

    path('event/new/<int:event_id>', views.event, name='event_new'),
	re_path(r'^event/edit/(?P<event_id>\d+)/$', views.event, name='event_edit'),
    re_path(r'^all-event-list/$', views.AllEventsListView, name="all_events"),
    # path("all_event_list/", views.AllEventsListView.as_view, name="all_events"),
    # re_path(r'^event/approve/$', views.event_approve, name='event_approve'),


]

finalproject/finalproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings
from rdv.views import (
    rdv
    ) 

from account.views import (
    home,
    # settings,
    ProfileUpdateView,
    prof,
    registration_view,
    account_view,
    logout_view,
    login_view,
    must_authenticate_view,
    registerlogin_view,
    activate_user,
)


urlpatterns = [
    path('',home , name = "home"),
    # path('settings/', settings, name="settings"),
    path('account/', account_view, name="account"),
    path('admin/', admin.site.urls),
    path('authen', registerlogin_view, name="registerlogin_view"),
    path('profile-update/<int:med_id>', ProfileUpdateView.as_view(), name='profile-update'),
    path('profile/<int:med_id>', prof, name='profile'),

    path('logout/' , logout_view, name="logout"),
    
    path('must_authenticate/', must_authenticate_view, name="must_authenticate"),
    path('register/', registration_view, name="register"),
    path('activate-user/<uidb64>/<token>',activate_user, name='activate'),


    path('rdv/', rdv, name="rdv"),

    path('admin/', admin.site.urls),
    path('', include('cal.urls')),
    path('', include('medecin.urls')),
    path('',include('historique.urls')),
    path('',include('staff.urls')),
    path('',include('annonce.urls')),


    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='account/password_reset_done.html'),
     name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='account/password_reset_form_password.html'), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='account/password_reset_form.html'), name='password_reset'),
    
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='account/password_reset_complete.html'),
     name='password_reset_complete'),
    ]

from django.conf import settings 
from django.conf.urls.static import static    

urlpatterns +=  static(settings.MEDIA_URL, document_root =settings.MEDIA_ROOT)

finalproject/historique/urls.py
from django.urls import include, re_path,path
from .views import hist,hist_perso, ordo_pdf,ordonance

app_name = 'historique'
urlpatterns = [

path('historique',hist,name='historique'),
path('hist_perso/<int:id>',hist_perso,name='historique personel'),
path('ordo/<int:history_id>',ordonance,name='ordonance'),
path('pdf_ordo/<int:his_id>',ordo_pdf,name='pdf ordo'),]

finalproject/historique/models.py
from datetime import datetime
from django.utils import timezone
from operator import mod
from django.db import models
from cal.models import RDV
from annoying.fields import AutoOneToOneField
class history(models.Model):
    rendez_vous = AutoOneToOneField(RDV,on_delete=models.CASCADE,related_name='rendez_vous')
    observation = models.TextField(null=True)
    diagnostique = models.TextField(null=True)
    lettre = models.TextField(null=True)

finalproject/historique/forms.py
from django import forms
from .models import history


class ordoForm(forms.ModelForm):
    class Meta:
        model = history
        fields = ['diagnostique','lettre','observation']

finalproject/historique/views.py
from calendar import c
from ctypes import alignment
from datetime import datetime
from email.utils import parsedate
import imp
from itertools import starmap
from django.http import request,FileResponse
from django.shortcuts import render,get_object_or_404
from .models import history
from account.models import Account
from django.db.models import Q 
from .forms import ordoForm
import io
from reportlab.pdfgen import canvas
from reportlab.lib.units import inch,cm
from reportlab.lib.pagesizes import letter
from cal.models import RDV
from django.utils import timezone
def hist(request):
    search_name = request.GET.get('search_name')
    search_date = request.GET.get('search_date')
    search_hour = request.GET.get('search_hour')
    search_ville = request.GET.get('search_ville')
    page = request.GET.get('page')
    listt = RDV.objects.filter(Q(start_time__lte= datetime.now())).order_by('-start_time')
    for e in listt:
        print(e.rendez_vous)
    if search_name or search_ville:
        listt = listt.filter(Q(Sender__first_name__icontains=search_name) | Q(Sender__last_name__icontains=search_name))
    if search_date:
        search_date1 = datetime.strptime(search_date+' 00:00:00.00000', '%Y-%m-%d %H:%M:%S.%f')
        print(search_date1.day)
        listt = listt.filter(Q(start_time__year__icontains=search_date1.year)&Q(start_time__month__icontains=search_date1.month) & Q(start_time__day__icontains=search_date1.day))        
    return render(request,'history/historique.html',{'listt' : listt})
def hist_perso(request,id):
    if id:
        instance = get_object_or_404(Account, pk=id)
    historique_perso = RDV.objects.filter(Q(Receiver=request.user)&Q(Sender__id=id)).order_by('-start_time')
    return render(request,'history/hist_personel.html',{'hperso': historique_perso,'patient':instance})
def ordonance(request,history_id):
    his = get_object_or_404(history,pk=history_id)
    form = ordoForm(request.POST or None,instance=his)
    if form.is_valid():
        form.save()
    return render(request,'history/ordo.html',{'historique':his,'form':form})

def ordo_pdf(request,his_id):
    _W, _H = (21*cm, 29.7*cm)
    A6 = (_W*.5, _H*.5)
    buf = io.BytesIO()
    p = canvas.Canvas(buf,pagesize=A6,bottomup=0)
    textob = p.beginText()
    textob.setTextOrigin(cm,cm)
    textob.setFont("Helvetica",12)
    ins = get_object_or_404(history,pk=his_id)
    lines = [
            "                      ORDONNANCE",
            "",
            "De la part du Dr. ____________.",
            "Spécialité : _____________.",
            "Jour : " +ins.rendez_vous.start_time.strftime("%Y-%m-%d"),
            "",
            "",
           ins.observation
           
    ]
    for line in lines:
        textob.textLine(line)
    p.drawText(textob)
    p.showPage()
    p.save()
    buf.seek(0)
    return FileResponse(buf,as_attachment=True,filename="ordo.pdf")
# Create your views here.

finalproject/templates/history/hist_personel.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Wai+Doc</title>
    <link rel="stylesheet" href="{% static 'bootstrap/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'historique/histo.css' %}">
    
    
        <!-- Font Awesome -->
    <link
    href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
    rel="stylesheet"
    />
    <!-- Google Fonts -->
    <link
    href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
    rel="stylesheet"
    />
    <!-- MDB -->
    <link
    href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/4.0.0/mdb.min.css"
    rel="stylesheet"
    />
</head>
<body>
    <link rel="stylesheet" href="{% static 'new_home_page/css/homepage1.css' %}">    
    {% load custom_tags %}
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-light fixed-top bg-white">
     <!-- Container wrapper -->
     <div class="container-fluid">
       <!-- Toggle button -->
       <button
         class="navbar-toggler"
         type="button"
         data-mdb-toggle="collapse"
         data-mdb-target="#navbarSupportedContent"
         aria-controls="navbarSupportedContent"
         aria-expanded="false"
         aria-label="Toggle navigation"
       >
       <i class="bi bi-list"></i>
       </button>
   
       <!-- Collapsible wrapper -->
       <div class="collapse navbar-collapse" id="navbarSupportedContent">
         <!-- Navbar brand -->
         <a class="navbar-brand mt-2 mt-lg-0" href="#">
           <img
             src="{% static 'img/logo.svg'%}"
             height="25"
             loading="lazy"
             
           />
         </a>
         <!-- Left links -->
         <ul class="navbar-nav me-auto mb-2 mb-lg-0">
           <li class="nav-item">
             <a class="nav-link" href="/" id="coloritems">Home</a>
           </li>
           {% if request.user.is_doctor%}
           <li class="nav-item">
             <a class="nav-link" href="/calendar" id="coloritems">Calendrier</a>
           </li>
           <li class="nav-item">
             <a class="nav-link" href="/all-event-list" id="coloritems">Liste d'attente</a>
           </li>
           {% if request.user.is_authenticated %}
           <li class="nav-item">
             <div class="dropdown" >
             <a class="nav-link" id="coloritems" href="{{lien}}" data-mdb-toggle="dropdown" aria-expanded="false">
                 Historique
               <div class="dropdown-menu" style="width: 250px">
                 <form class="px-4 py-3" action="">
                   <div class="form-outline mb-4">
                     <input type="password" id="form2Example2" name ="pin" class="form-control"/>
                     <label class="form-label" for="form2Example2" name ="pin" id="pin">Code pin</label>
                   </div>
                   <button type="submit" class="btn btn-primary btn-block" name="submit">Entrer</button>
                 </form>
             </a></div>
           </li>
           {% endif %}
           {% endif %}
   
           
           <li class="nav-item" >
             <a class="nav-link" href="/listpage/" id="coloritems">listmed</a>
           </li>
   
         {% if request.user.is_staff%}
         <li class="nav-item">
             <a class="nav-link" href="/staff" id="coloritems">Staff</a>
           </li>
   
         {% endif %}
   
         <li class="nav-item">
             <a class="nav-link" href="/general_info" id="coloritems">General info</a>
           </li>
   
         <li class="nav-item">
             <a class="nav-link" href="/subjects" id="coloritems">Annonce</a>
           </li>
   
           
         </ul>                      
         <!--<div style="padding-right:30px"  >
           <button style="border-radius:15px;background-color:#4d47c3;color:#fff;
           height:36px;font:caption"><a id="colorbuttonw">Vous êtes un professionnel de santé ?</a></button>
         </div>
       -->
         <!-- Left links -->
       </div>
       <!-- Collapsible wrapper -->
   
       <!-- Right elements -->
       <div class="d-flex align-items-center">
         <!--icon-->
             
         <!-- Notifications -->
         {%show_notifications%}
         <!-- Avatar Account -->
         <div class="dropdown">
           <a
             class="dropdown-toggle d-flex align-items-center hidden-arrow"
             href="#"
             id="navbarDropdownMenuAvatar"
             role="button"
             data-mdb-toggle="dropdown"
             aria-expanded="false"
           >
             <img
               src="{% static 'new_home_page/img/user.svg'%}"
               class="rounded-circle"
               height="50"
               alt="Black and White Portrait of a Man"
               loading="lazy"
             />
           </a>
           <ul
             class="dropdown-menu dropdown-menu-end"
             aria-labelledby="navbarDropdownMenuAvatar"
           >
             <li>
               <a class="dropdown-item" href="/account">Mon profile</a>
             </li>
             <li>
               <a class="dropdown-item" href="/logout">logout</a>
             </li>
           </ul>
         </div>
       </div>
       <!-- Right elements -->
     </div>
     <!-- Container wrapper -->
   </nav>
   <br><br><br>
    <div class="row">
        <div class="col-lg-3">
            <div class="card">
                <div class="carte rounded left mt-2">
                    <div class="card-block text-center text-black">
                        <img class="user-icon mt-5" src="/images/id-card-solid.svg" style="height: 20%;width: 20%">
                        <h4 class="font-weght-bold mt-4">Name : {{patient.first_name}} {{patient.last_name}}</h4>
                        <p><a href="#" class="text-decoration-none">Email : {{patient.email}}</a></p>
                        <p><a href="#" class="text-decoration-none">Téléphone : {{patient.phone_number}}</a></p>
                        <p><a href="#" class="text-decoration-none">Ville : {{patient.ville}}</a></p>
                        <a href="#"><i class="far fa-edit fa-2x mb-4"></i></a> 
                    </div>
                </div>
                <div class="card-body">
                    <div class="text">
                        <ul>
                            <h6><span class="text2">Antécédants médicaux</span></h6>
                            <li>First</li>
                            <li>Second</li>
                            <li>Third</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm">
            <nav class="navbar2 navbar-light bg-light mb-2 pt-2 pb-2">
            <div class="container-fluid">
                <form class="d-flex">
                    <input type="date" id="myInput" placeholder="Tapez la date">
                    <input type="time" id="myInput" placeholder="Tapez l'heure souhaitée'">
                    <button class="btn btn-outline-success" id="bouton" type="submit">Rechercher</button>
                    </form>
            </div>
                <!--one occurence of the same profile-->
                <ul class='list-group-flush' id="myUL">
                    <!--one profile as such-->
                    
                        {%for rdv in hperso%}
                        <li class="list-group-item" style="background-color: light;">
                        <div id="profile">
                            <a class="inner" id="text-consultation" style="height: 50px; text-align: center;" href="#">{{rdv.start_time|date:"y-m-d"}}</a>
                            <a class="inner" id="text-heure" style="height: 50px;" href="#">{{rdv.start_time|date:"h:i"}}</a>
                            <a class="inner" id="text-ordonnance" style="height: 50px;" href="{% url 'historique:ordonance' rdv.id %}">ORDONNANCE<i class="pen-icon fa-solid fa-pen-clip"></i></a>
                            <a class="inner" id="text-view" style="height: 50px;" href="{%url 'historique:pdf ordo' rdv.id %}"><img src="/images/eye-solid.svg" class="view-icon"></a>

                    </div>
                    </li>
                        {%endfor%}
                    
                </ul>
            </div>
        </div>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
</body>
</html>

finalproject/templates/history/ordo.html
<!DOCTYPE html>
<html lang="en">
<head>
  {%load static%}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Wai+Doc</title>
    <link rel="stylesheet" href="bootstrap/css/bootstrap.css">
    <link rel="stylesheet" href="Historique/ordo.css">
    <!--Font Awesome-->
    <link
    href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
    rel="stylesheet"
    />
    <!-- Google Fonts -->
    <link
    href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
    rel="stylesheet"
    />
    <!-- MDB -->
    <link
    href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/4.0.0/mdb.min.css"
    rel="stylesheet"
    />
</head>
<body>
  {% load custom_tags %}
  <link rel="stylesheet" href="{% static 'new_home_page/css/homepage1.css' %}">    
 <!-- Navbar -->
 <nav class="navbar navbar-expand-lg navbar-light fixed-top bg-white">
  <!-- Container wrapper -->
  <div class="container-fluid">
    <!-- Toggle button -->
    <button
      class="navbar-toggler"
      type="button"
      data-mdb-toggle="collapse"
      data-mdb-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
    <i class="bi bi-list"></i>
    </button>

    <!-- Collapsible wrapper -->
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <!-- Navbar brand -->
      <a class="navbar-brand mt-2 mt-lg-0" href="#">
        <img
          src="{% static 'img/logo.svg'%}"
          height="25"
          loading="lazy"
          
        />
      </a>
      <!-- Left links -->
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="/" id="coloritems">Home</a>
        </li>
        {% if request.user.is_doctor%}
        <li class="nav-item">
          <a class="nav-link" href="/calendar" id="coloritems">Calendrier</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/all-event-list" id="coloritems">Liste d'attente</a>
        </li>
        {% if request.user.is_authenticated %}
        <li class="nav-item">
          <div class="dropdown" >
          <a class="nav-link" id="coloritems" href="{{lien}}" data-mdb-toggle="dropdown" aria-expanded="false">
              Historique
            <div class="dropdown-menu" style="width: 250px">
              <form class="px-4 py-3" action="">
                <div class="form-outline mb-4">
                  <input type="password" id="form2Example2" name ="pin" class="form-control"/>
                  <label class="form-label" for="form2Example2" name ="pin" id="pin">Code pin</label>
                </div>
                <button type="submit" class="btn btn-primary btn-block" name="submit">Entrer</button>
              </form>
          </a></div>
        </li>
        {% endif %}
        {% endif %}

        
        <li class="nav-item" >
          <a class="nav-link" href="/listpage/" id="coloritems">listmed</a>
        </li>

      {% if request.user.is_staff%}
      <li class="nav-item">
          <a class="nav-link" href="/staff" id="coloritems">Staff</a>
        </li>

      {% endif %}

      <li class="nav-item">
          <a class="nav-link" href="/general_info" id="coloritems">General info</a>
        </li>

      <li class="nav-item">
          <a class="nav-link" href="/subjects" id="coloritems">Annonce</a>
        </li>

        
      </ul>                      
      <!--<div style="padding-right:30px"  >
        <button style="border-radius:15px;background-color:#4d47c3;color:#fff;
        height:36px;font:caption"><a id="colorbuttonw">Vous êtes un professionnel de santé ?</a></button>
      </div>
    -->
      <!-- Left links -->
    </div>
    <!-- Collapsible wrapper -->

    <!-- Right elements -->
    <div class="d-flex align-items-center">
      <!--icon-->
      

      {% if request.user.is_authenticated %}

      <!-- Notifications -->
      {%show_notifications%}
      <!-- Avatar Account -->
      <div class="dropdown">
        <a
          class="dropdown-toggle d-flex align-items-center hidden-arrow"
          href="#"
          id="navbarDropdownMenuAvatar"
          role="button"
          data-mdb-toggle="dropdown"
          aria-expanded="false"
        >
          <img
            src="{% static 'new_home_page/img/user.svg'%}"
            class="rounded-circle"
            height="50"
            alt="Black and White Portrait of a Man"
            loading="lazy"
          />
        </a>
        <ul
          class="dropdown-menu dropdown-menu-end"
          aria-labelledby="navbarDropdownMenuAvatar"
        >
          <li>
            <a class="dropdown-item" href="/account">Mon profile</a>
          </li>
          <li>
            <a class="dropdown-item" href="/logout">logout</a>
          </li>
        </ul>
      </div>
      {% endif %}
    </div>
    <!-- Right elements -->
  </div>
  <!-- Container wrapper -->
</nav>
<br><br>
    <div class="ordonnance mt-5">
        <form action="" method="POST">
          {% csrf_token %}
  
        
            <div class="accordion" id="accordion" label="">
                <div class="accordion-item">
                  <h2 class="accordion-header" id="panelsStayOpen-headingOne">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseOne" aria-expanded="false" aria-controls="panelsStayOpen-collapseOne">
                    Diagnostic
                    </button>
                  </h2>
                  <div id="panelsStayOpen-collapseOne" class="accordion-collapse collapse" aria-labelledby="panelsStayOpen-headingOne">
                    <div class="accordion-body">
                      <label for="fname"></label>
                      <textarea type="text" id="input" value={{form.diagnostique}}></textarea>
                    </div>
                  </div>
                </div>
                <div class="accordion-item">
                  <h2 class="accordion-header" id="panelsStayOpen-headingTwo">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseTwo" aria-expanded="false" aria-controls="panelsStayOpen-collapseTwo">
                    Prescription
                    </button>
                  </h2>
                  <div id="panelsStayOpen-collapseTwo" class="accordion-collapse collapse" aria-labelledby="panelsStayOpen-headingTwo">
                    <div class="accordion-body">
                        <textarea id="input" type="text" value={{form.lettre}}></textarea>
                    </div>
                  </div>
                </div>
                <div class="accordion-item">
                  <h2 class="accordion-header" id="panelsStayOpen-headingThree">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseThree" aria-expanded="false" aria-controls="panelsStayOpen-collapseThree">
                    Commentaires
                    </button>
                  </h2>
                  <div id="panelsStayOpen-collapseThree" class="accordion-collapse collapse" aria-labelledby="panelsStayOpen-headingThree">
                    <div class="accordion-body">
                        <textarea id="input" value={{form.observation}}></textarea>
                    </div>
                  </div>
                </div>
              </div>
              <div class="bouton">
                  <div class="container">
                    <button type="submit" class="btn btn-outline-light mt-5" id="valider-ordo">Valider</button>
                    <a href="Ordonnance.pdf"><button type="button" class="btn btn-outline-light mt-5" id="valider-ordo">Aperçu<img class="view-icon" src="/images/eye-solid.svg"></button></a>
                    <a href="{%url 'historique:pdf ordo' historique.id %}" ><button type="button" class="btn btn-outline-dark mt-5" id="telecharger-ordo">Télécharger<img class="download-icon" src="/images/arrow-down-solid.svg"></button></a>
                  </div>
              </div>
            </form>
    </div>




    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
</body>
</html>